steps:
  - label: 'run the cardano node sync test on Mainnet using a Linux machine'
    command:
      - nix-shell --run 'python ./sync_tests/sync_test.py -t1 "1.26.1" -e "shelley_qa"'
    branches: "dorin/*"
    timeout_in_minutes: 1200
    agents:
      system: x86_64-linux
      queue: benchmark
    artifact_paths:
      - 'logfile.log'